---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sa-platform-catalog-service-secret
  namespace: sa-p8-stage
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBsxFGw9nMGZcpIa6HySG7CdpajrLAIgEMB9CmNWEw+5rVZa9PFaLEoV+OE5KhSIt3d04FbWWjYAoKg7y7DhXwy6FaiPRoPKSVg499rKyq0IDo0xwfexQIYSnyIFZ0v4j645/8P+/GRuCHf09aVNPGXIkqFqoyzMR21Mngk8RXOECgmObUAa5LxDrXmDMhSS+QDUEY6p8QI/mUL2Lqv45jHir5lI2+by1AGm0hebC25IHeqIhDKczXEdHXFWhrjfaYbyID+++dN2+nc4iUjqv6g6xjkI+pNZZv8+w5+RGM7rzngyfuBFh7A5Y1zoqx2JwaHNFZYYO1RGBk2ZHOqyO/GwjQJ7wCGbQA1C6T0ZujaD3getY/+yAZ37xlsxvO6pSfVCAmIrxO/3MFhi6bvfvMQTRUyPwnSEYnVOMvutqNwmg9jteVEuxLJAv9mBQTRw+vSrXmJV0zhJ62ayeTfgErXRDGTW0t95JS/X/ZldrhPjyqg9lpPI6ESw0O5YxzT5Ukufe/qswxb04ofKGQSK1u4r8zequxOjqUN701+waXt/Gvzvr8aOb+c1tQ16yrzmpLcqhlIcAYtdtDURCREs7r8w4HpH/tOy9z/AbuIzzzHHgIHT5x++8GT+KaOjySCv9caOg+XxdjSoGdL7SU5PKOWjM2LeBdk8Oifj9BvYRJ+SWHVdYG1n2bLbFejj34nSgGEliEr0yogW/HeMaxJDxYc6A2okhtihm1zXAo8pWIanw==
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: sa-platform
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: sa-platform
        app.kubernetes.io/part-of: sa-platform
        app.kubernetes.io/version: 2.0.0
        helm.sh/chart: sa-platform-3.0.0
      name: sa-platform-catalog-service-secret
      namespace: sa-p8-stage
    type: Opaque
