---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sa-platform-notification-service-secret
  namespace: sa-p8-stage
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgABETkEhCmnl/k7S6n1dRypGoYTSiMOcUIEDMa3HsoBwjTlcIndhbiMt5Hm7z16aR+6EFffRDKzM4Zrvxb5qxUC0kKvo1a2oYSoKkzgrjNqgeQC42kKP6Y5Xcoes9zeZy/DvVHa+u31czU+n/2wniVH7wjDQ63oIKJuYmj5Wpl0CY57Zs32V3p6SwlJanO6BzWzVkfgshqxQ2B1xM4VBEqBu56nqyofQ5CQGCQEaK9kzPZ0tVcmb5ZlFiNSOehaLeLglzn+CC1f7uDYKOU2AepC6O7Z/wksBRO0QkEuxz6axXY9LNQy4Hmh0chZ6+gt/N5MzT5AHbb1cOWAYqRich6xx5mZwLazNsq3dmUSapCDutWGuqo3vHzeTDyUBqXZLWKDa552P06GKJ5/1PmzRsvUhQyXcKtNNdylix5nvKXoK0SXR/58JnUXyUhcxjPOuwJV0lej+kmudLCbwZ+iQzCcXyooqpIEwpD1s0Yi3Skvxl0u441Y0aPJawokz3NI41/qH3hYYM2ZzZLpUUMMP0MJn5QWB59RBHNmslEhoArKLA2D9YBVjD/wZla+q+QkdOd3K0anIuO81syDhJct4YJwG01rpO+OBypkVjfoWt+Ya89QhlVCDT2Qde+OJW45uZN4JkVzJjxpE6ucNBsZ1or+uYr+FRf78yIHk7iYcNPMUDkcmuckORaHkWY815z3jZ7FAjjkovpIdBMKGQovQj5k7ct/PYwioHxObZVbgsAYEg==
    RABBITMQ_PASSWORD: AgA0yVswIBdl27E4Yfto1JGcVVaedvdbyE81nMeeg8CnQPcWXhBfuZGy4zKjNjQIFVjh+PbKqaRYMAjS+w7tUyMLfgzSVSTzEr8/uDv4zw9TzQ63Orf2PS3nHPt7dx1mF8eWY0Pe2DBVTJJAXKBt5TL3yL7+N1SEsK/I7tk2oS3rf6o0tlod/caAfNgm4vY1eQP7rgYf61nwrnG5WMqrpy2Qm7LAq8IeRIj8MSfAO7RBk6COJq6JdEw35KMgqh9mRiau/K7liMw4YE54IPi5LqJTV54i5pm1vKzBz3HFZp4U56RUdhcrbiD3g8fTdVbSeqEGRRspJfVtz/qG7t4lUf8QjsqeDTyxh9cv3+igMD8hJYSZrnnCdlw8Vv8O0NgJHLiX6NTOlZE3MyXsT+f8dSAUZKlL59ZfPU3vV7Y50PnY6CFXKYzd2nTiXgNZmMOvwXMrwy9ulxIOjbOnjP38k9B4QQqPyFMR7azg0HQsvlkQGqPjPgWWkFpV+YK82j0fD5N7cKLPA21SyvFNQoM0MIVmRojNQs/jCnHZbLF7UDFdMnyZB1TZjZJw90i9xvFzRY4mWPN/ZGX9UUqJXbJj/i9nf7KiWpIDD/6lmK1iZ0566ZrNRvtanu7nOG5amJ6uiLWBdxDDFoK93KrHolXWS7BuGOXNIQlXr4Idbu3RRAdGqaLUVx0p1vvnSf7mPZgT0k/Hs199Wfp0Vc+xsmzhj05o68TuOKWH6q1iIPBF0U0eRw==
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: sa-platform
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: sa-platform
        app.kubernetes.io/part-of: sa-platform
        app.kubernetes.io/version: 2.0.0
        helm.sh/chart: sa-platform-3.0.0
      name: sa-platform-notification-service-secret
      namespace: sa-p8-stage
    type: Opaque
