---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sa-platform-broker-credentials
  namespace: sa-p8-stage
spec:
  encryptedData:
    rabbitmq-erlang-cookie: AgA1gCj2RcqPxijZ5Fs+w6jVKPy7kCIVJd/IX1eXLCmjmFDcuHSEXlPaVzB9bDyUX1Z5hzHfhq/gh7Kmk9bMwT+uTM3yR0xJKd6BqRTw8NcI9KvBh1CvgeL7OYg2vEmIUlaOyasikHFwrX+MZk8Z9IkATct1xEcT6trSvHOokVzpeoIYxd4RQtQcUS6o9OgYStCUaxJ7n6thaGPF9pSjWJH0fiAIS/zaoMptxR093OqKQ3pUpow/gFKgUAxekmApCzKa0vJlFPCmXhq/f7NUHRG5BHyb6fYszqzPtSd3LwDYAdPxoc1s3oZQs6jIju/OctTKH7zFopcxwD7J5oFm45YlqCd3WFN8sYyFciaeC45Unu90r79HIMKxyQnMTf3vBpSfcRxij2G5LzICjb4p7iq2jU2vcS5YR6ZJf4k1lY+A1pIXerOiSVRTWJDyGLrxXktRH8GD1W4UCaqkg6F37qYPcsEJqSfZ0x5B2qyMDCUKb7+oAmcd+3A/dn7jMu/ukQJ5TqOps/fo6Fq+o7JSreNpRxIze3Xafua+6pD9ep39hofrYK08F1MiNjeltsksaG1pSE99eZouF8j+P8bj/wnKFI2YvrFeDpJp8ZRgzAimkr7zV9b8iCAkQGV8AXtLeLVO976w9YDtIQ+MG7equ0iJduirk7j0/hrcFFMTe6oqQTVhIi26F++PLo73UOIfAb6OpwGyiiSbMnXTmo/Bl7GursEfKUMlm6p2bgyITYBYBQ==
    rabbitmq-password: AgB+/mRwCA337mc/ToLV1lWUwTBzWVG89E8AFasVnEp00oDc02iNkpIxH/h7FjzI8bBjn6C31z453dkJgC6rZBQgfHBxgcl17gnbZaWWNXRQ5gjJFfVankcxMUxaEPdvxbT9Cf04ekWa6azoHvwPvv3LwvRrMtsigAEeMTnLkRVpvjM+6o8ekh1r18s/Y0EtSChYveuSPnx9+rsWRCClPEUPRhmuVu05VN3g4r718nmdvZO835YA4S4QRaRCOWM0uwlWMfk7mZbwrb7a2cm5lQrsKkduRSuPzHAxGcV+WosRUaqBwWYJWtTNc0xjU83aEPZSswo+yNX8YvP0pKC19Zihvp1ZzGUQmWIYV95/plSuu1f5ryT13K1m++IQvCTkh+E5KYq0TBawCRGKtvwlcHMu1tXCt2v3suaG3pOaVDGp9s/BNMXI5mhpn1a19lI0AZu7VCiz6e3siKIq0DdtbrarJCxDxp+5DYR7tlWhbxr5xLAmEs5UMwEhz52eav5yeS1WmznWCLUHOAbreni27gvBjsnSC9laeLN230GAWcL8A/m2JQAIiVoiFFt93pHFAmj6IVa59ELzf49SkZAUeTOlOs65TPfqtn/nWNig2KTrv2ShfpTA25PgqJW8hLlbniwXphUeAsh2wQ749pnmYIy6qRQk0xR7hf41dCAKah0mYbgPhTIqMHBWJmBUdwbz+yJc5PRPCg+iYhMG5B292296a5oJ7g6WYjDSQdkmP5j/cw==
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: sa-platform
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: sa-platform
        app.kubernetes.io/part-of: sa-platform
        app.kubernetes.io/version: 2.0.0
        helm.sh/chart: sa-platform-3.0.0
      name: sa-platform-broker-credentials
      namespace: sa-p8-stage
    type: Opaque
