---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sa-platform-order-service-secret
  namespace: sa-p8-stage
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAaqtax7D3nOEa4HwfCCLl7pOLSujseYJ8O0GxvYSGa6Z4FFUC3SdHDlxs/Z3cbDYYzP7aWsjHH89ygFCG+OasNCR4Ki6QViMa0Cz1URO+NWSzeOxFr4I+hZmMJt0tlIw0Je818jMo76NCN2MIzGflm1isxJUxcQF4FJAltAvqsVM4cVHeGownyfD2jq59GmX47qH4d6pdbptJYiuGR8BXX8F+m7B2Ov4NzmRwpmjH74OVNL114l8jbuw13ZFKLr66puNiuEVDhcI0oyhRox5JIiWHjmutGcfdTqlMI4PW7OoAO0VUaqPX9LyAKLrijh8JOrYZ6HikBOiJBINGU01g9s/iIRUwkyNbs4X/4Y0x9d5Ag33yg2LW+d3uiBPfQ92m24+H+PVToLN7xckil3vpmtOdj2NuGPEQgFGqI1lFldSpuuZC+Iy2KX/PRzqQlu4jYRtxb0qzm4FTiHnjiPzqPCM3xBf3okQIjWaFH7cXnGbY/go8dTuynTBXbh1/z8n+A3XrCDGtiExFd/gkl7tHVuctS1NEPlkWXT/OX6TICUovb+U7qdWDNoy+nybaMS4q7J11aTbH9YMJuE8z70spi36y71CD9V/98hVdNPkzRci5mQ69nu9lR0dKYWsrLFN1RPnh6jxnUBfpQF13O3M+nGQewKW3IzM+ufxR/jVgP+w6OXw+nkS8emwxOOLhAhmGo5TSv71jHCUkPzCMKjo7cq/re7N66/t8NyydB+v15tw==
    RABBITMQ_PASSWORD: AgBDPXquz9GhUJLxttp7l06J0es/Ce4oexltp0pPvmX1J8KCj2He64VxLV7CzE7GKNL7x6KXZrXnVvaiVNzd4rtK4ObXSxPTP2kcEMl2u3ABKZOwqo882BapUNPO3aQ4LQyiM/LibMESm/i9LKIZSQSnQlTehAaHV5aLd/j5VAoBb3VqYlwezs1134G0E8SVgGGZD/LMxO2ii0RPuV3El+R2VBbxdADjFcDAbw5NRqRW5XkeDLr1CdHXzLEX06gLmI/ixHgTmDKeNaj2UeRoXNl1WZ77GO2CE/NKA+eFlCb67/G7jsdhEXVaG1O6F2Pe/kRLKx6UpX91a7GQElcDdqaMURuPwdeNAObua0NLInsfloUJbdimA3pY8tGtv5hcOGx40o38mBBTqtOlVtt60wXZIuoYFRA8tllrnt4Mwt4+PKBLHIZYchLo1pd8Ok9ND9yx8bUU664kWV3+IBlFwBmw8uL6cJu5bvj7O96c9PTft39M67Bq0/qToD/6RQ/6vnVy2d1aK5wDB4SRpOCg4TPJd69h7EDuXqCPkIfphAXJ+IBIOcNuDp4gDwjSGlYMaiXNHcRDmNFZ285zdrNF/JYhaEGx8FAsAjQ/dMRgXhSqNguEl2fyd6JUD+pFj2BzwKNuevaOcQ6p2Sjiuc3GcV+jz/UdUH5TMa14QIzsV5LqjFNaoVWxdr9A7g5v+9KjQzfCu+qbLfEg9liTvbvgo4hWUt9BhlNxKfbgfEmGXY1Ykg==
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: sa-platform
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: sa-platform
        app.kubernetes.io/part-of: sa-platform
        app.kubernetes.io/version: 2.0.0
        helm.sh/chart: sa-platform-3.0.0
      name: sa-platform-order-service-secret
      namespace: sa-p8-stage
    type: Opaque
