---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sa-platform-heartbeat-writer-secret
  namespace: sa-p8-prod
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBpwl4Rkk7pQeD2AWL/3dJlZxVuALd843y55WgpwhLDu5zvXYII2wMlUhaL2jafi2mE0GGTrD1CNErKUhoBlDzmzo8W0lHi0U3unT6bmvTfF5cYw00SGIOPkzHi4dwUCJwVLoWXqC9R/1hQmnyLmb5XAiMr5eRoXyWVhR3+OlzrEMjDGIH6UTS7i0Au8wLRoojfDaZ1y2d1hoCKzZEfb3dW5H3H6Cp/DQ8DmNTnkdRoaURNT9sbrgrTBXnMQXQEDM8xV6FMxfJcrZH9oyhMQBBNtVD3Z+r8G349lpsFnL+dzLcOg8/Bd/GspR5SPX3OVdaFokG5l5jBQHKlJ4DnvteePFFaYasOl/eFO8U9rYBc7BFRneymnQjZCYrk9X/gbjSqI7A3xWAO5mvgs0WnO2iEM7uitlGcf/lKiXqgXNrb3QWzpGKsHtHYXbi5CT8RuE1OCv0iUptpajNpaQ/JmmtQ61fJTdGiICQqhJIGSLhHIPyDlWxY4emuGaw92uwJuk6CKgEMXRLB6VKpL7FHEan3P4rZ1+kPdFzq3xG/4gg0J/fQ2n4xGqsgoAikMVNJUFkS/lDl2YfRE9kxNUvFJB0CpCOv4w94mLM4vwk2T8BSdQl93BChOyOg1cwV+Y9/g0gcGa83jJIxmyH0rso4ht3IViL/hoA53nQtDJ4NgIvtRK+BoNYhw0J+OOSWJVKvNgjnv7CHZkh/x8Q/Cm6+8zN/FTD8fXc28uwT19LBfv5Ogg==
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: sa-platform
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: sa-platform
        app.kubernetes.io/part-of: sa-platform
        app.kubernetes.io/version: 2.0.0
        helm.sh/chart: sa-platform-3.0.0
      name: sa-platform-heartbeat-writer-secret
      namespace: sa-p8-prod
    type: Opaque
