---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sa-platform-notification-service-secret
  namespace: sa-p8-prod
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBpRV0WqzT7qBJBJ9ieBhzlq0KNzhjfjqBgVpDRyY7tCD16TMZdEG7fzuObsrKry03Oe/x6AGvrfywyxKIIoTyA+ZIugCpbek4cYYyNLUIyBUe6yffD6zpPc7++k5f1SbVmvxmiXWh18IUb9b2Dv2Y3jVk5yR4g7PlkdRWxUI+Ry6foXoKG46nasp/4gEHARGGMerVpV1kb4RPwilIpMWmwsSEG7cNM+gB0OMi1UsJXricQsp7wMApiPxvLmBbGq6InRaRaU19AB1T1RmMkMj6PdV3Se0nAzw4fbhWnG9/PzO/UxZA5J84PRrRfwfeUF2s//qESQxXFBmmkEX2EvR7xauBH5dOBHGfKlAbwaI0M9gdiRXM0fg0E2DF4bodfa+E73G1H2QOPcR8TTFTW46MgkRObMmLZqmW35+FOCVzgXILUnuI2jFkOnzoeYTR/ZSA/avSwElTFM+x29RzTFUcVU4gy5xZZVwj8vHOiQkHRCd9RJYqUMZC9LIAGe2J+PdH3m3cpTAq/jEDztGMTlA29fEcsxvjGaM3eMbh7yM2v3T5AqwppA1e/Mv4dq3XrpwyinUVf3+0ZHNVL5Xlfy5LWeGkz8vVXnr/n0mvKn88LICKmLeO7867X1soHiKWzuxPcIhsZyMLb2qw8Iut23Ee/3aXUa0+QMc2rg8xOBbjGVyL0Q5ofwuGynwRZqb5xIBC+cLoNIBewPaQVlGOBNfFPxSOG19n+bTWNfW8MTq2Xkg==
    RABBITMQ_PASSWORD: AgA+WdMfqJ3beTx7fBnKN5dLWOrM5pWM3Jfv5SfiijZNNYpzNb77xDlNbKnwRdpte9t7i1+H725A2fhGYgwheWFPacAM8KtdsGZHAzYulIlj2VKUFPCg46RQhR+Z56v6ebU7rahvfvER57I8swxkpC2XLthSc1U01B4xTNR+eWwBHW5oyC+r2aOtIL3A92Q4dfWQqtK/wY5QOAz6HTqga5dZ9iMpmUioeeEVsatsRDEFqI3wt/a03Jj93p8Ypt1tCLppriSV23Fr41y8xJEhDrnRHNZDzh8nPzseA+taMXVo+6dD4zMB5wqI79AUqueEI1LGmFC7Xya83QmOrlndPhtzyRmUUTWMfoI8vMXnrwVyHEu8N/KEMJnnvQRCdgKhS9dvlHpoUYuXmwpf8euB3i7SSK1Lbor/ivmdlkSqMxpirHPht0Uqz9t12aKUXBFnohbPPbqPMtWd9K+avJoy/vE9FlohO6/96ck+b57Syzu7NPLDlMKFS+MgnHz4KDRVCmTGzahilGU+yoOJGaqpPyk4xRHjjPf97i60X/wcAGTtdka4liEfskbYyVmp1X0qkUxiYwjnQRhu8GX18WTqEv91Q30lzgYmsQrsNyPnhGaiQ89oPzrNdG+KT/vzz1EdT3e/ocmVAG8X7aMXY3tTuNjYDc2xiF4D6gyk8iW3bHSi4MW3LTH0kxSNzhICL+st/GRPh3VYALBjh2GoALMiMCzDNjfL1zbS1O/BBIkDEbgqNw==
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: sa-platform
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: sa-platform
        app.kubernetes.io/part-of: sa-platform
        app.kubernetes.io/version: 2.0.0
        helm.sh/chart: sa-platform-3.0.0
      name: sa-platform-notification-service-secret
      namespace: sa-p8-prod
    type: Opaque
