---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sa-platform-heartbeat-summarizer-secret
  namespace: sa-p8-prod
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCeQjlFFSryVIg3Vs6VAePzrlpDqdhAZQqWBSIibLCPiiXU93Lb766PesJJ/X5RSpof3D0CyJtrOJHGaCBRhjcjv56Vp5CJKqf1hmb6tiI2Cw82vSY/wSYpvryWsqE64EyYskFqS/yEDFHU0jJPpw+7cWtS51qCqBk32MaHUQ9TZLqgxGhvFN1Vzgv+Tf0sExNQ5dAd07MkUo0zKiyD+4hPeSgXk+VB+5zLqqnEH3tP2WHHw5ygjmF8Sgd2TPo/6wQy2YRIxuflzENO8QWGUjZ1YoUxy1OpItR7PQJmCfhWXlpIiwjUsJw2psya5wyxnw95P+y5GwwkcHeYIYUTVgmPwpdfMvbx8GgAVmLAB3Upv9OvZ6LQM67O8yHW3sdpCQxnHlNHz4eDxk1qkzFx3vuHJ5Dhq/Vq5YERzyiZ5+Du1mAexGCXSMJfoiF42It9xpzK5tVCiNR+VPB5Eme5zkCujVVe0TMTJmYzN0fTw7F4OLnFanuoSzioTgrJfDp/w11mGs7aDMxuzpldJXKJr0ZU3cI7L4gyVAhVbrdEnMJQjVyEw7ziGXrv6Gyqa5sEOFjHn1MX86qFwbaBa/iGpeu0HaQcMxQu+9Ge3eHGH6m22PdsuVceXSLLRxXoHxft6ph7nwJwORvE/yZbfkutgXPZATaJ1JQUAYMYzk97Lht7Sbk6boeXnDeXcQey0gavXgGAtbzdPdfyf01U1FTQLn9n55Ky7SIvMeqS0zB+5NKTGQ==
    RABBITMQ_PASSWORD: AgAvVWaL6c57F6hImK/3HgXtlpRLpjWLSkClfI5v377aB+jsLm8MxrX/uOh6QJ5npbKKL7YJoLX0itLBKd5aLGYdMLf5z9LwUg5vcBDfJOr8JmjkyjBW0hAlQH/saG1/OsxQPN7aQTYm2GGgWPUXYqkICuo6CCCUnQ3Kh1OH46ABjM753xotXgZ+H3ioqR+YWhyDWpnFONjyxGHQ4/gtIdqUi/FJfsAQnlJ5j8uYUZeDiGHUdlR9XSiAEB5nWEiqoWr+LGnAc2UxnTsHGFvpir8E7Iwd+YN01UGOFV99x9sBsB2m56TiP75GtSH8tyHslp1QCsomZ8aeAldVeoq7OfY2P1MuwfCcFJsMd9zL5Ak3wrnq4gF8s8QQrQzShIKWqjgyygkWVc8YBSpLHaDIutNFvvQK7GZmgltmwYW4V5QdZpByGup8qNWOTedQtGsjkd1Ot4xMCRnzu9e33nSRtk7wr8HW49t8nMGz938SRnLOOJCYz89APPLdboigEp2lqOQEzXvF6ud/DcKB+EMo3505fZZxSdIHAMaHqhZ5VX3EywCLL75VRyEeV8CzQXDlwps4RSqwZXavLU7UUpoFTrVihnpMRdybFLjW7nNjuzy2zoCqj0Ct8W5HU/DotTpAmTYVO0W4M127WgEROXSRlSuRUrwUbpxO2msqYnUysiPUerHcZfEx3y077Wa2qndYVc+SHlarInc296T1NFxB6URJhSHUMS5hRuVBTb4EctUUNQ==
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: sa-platform
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: sa-platform
        app.kubernetes.io/part-of: sa-platform
        app.kubernetes.io/version: 2.0.0
        helm.sh/chart: sa-platform-3.0.0
      name: sa-platform-heartbeat-summarizer-secret
      namespace: sa-p8-prod
    type: Opaque
