---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sa-platform-order-service-secret
  namespace: sa-p8-prod
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBaWPamlW9FiMncmAY+U8JXwip9y49mU2cztDJssAKXmH8EMC5+IskioiNrGHEKhaPlL6NoF64Umi4gYyuz9W13f7s3XAP+AjFSCIpkAuCFUedbukRgSHvil9h0jk6P5m9yFwVRFf4P4trhKJcMuyr2uWdSBjOXluzvCy16AYCLka8K7h5JybC/fMgRXMXwaqEJ1w+nIgMnhZQCmk41z5FoDpIoTTPlkiVIbhmSVM0sECenxLEji5sKd/CS9JU/FiTw1/buxrRncS+DwYOWToWtUburGWOyeDKNl4MZGKpMEhxrTNezYigt2Y0MUwjhlRjB1G4PAfKm2WeoHj52n0v5ZFDPIwiFV2YV8NvbuyCwCt0RY3gRoiFMNq+dft2pavtSQ6FF1F8D4FnVfUtwxaJXAY3u1nR4oOVrZ+sPjdZEMNrEDXeWw7YqqUSuk54obz5FPQ5hF5v4zK96ODbRFjD53lPiXDsb2J966z5Ko17OQaUnCfpYi7mtd9vl9r24scrFNijzCLrrREhVGOWW5qhHlrkmyBghJuv7V0Q7bE3XWnvMjLevQpezkbuuaKos9wdCJip/ku+bul6BFHVd9gSslpFl3Kl3aP0NFjalrfUzARN0u8yEj7XEk3oUISLLwIo22ylCi8CD6TY6a+d+/KuFmaLj0TtmQuKCrXgw2CRRoeobBWln8nbicKDWpCD4QLD/C+yMp1f5xOwxkuJRDy8Rtgl5K3cCd0D17PRJlZ8d9w==
    RABBITMQ_PASSWORD: AgA+rSNY5qmFYaRvoJ04Rc2211TEm7xG5jNtsxjd+fsiUvXOsL81tT2iVLhghcahDB5++fca3z/P39r1WQHHV4ruI6Gw62GNlMQk3fslA6bTKOiPv5XmJ9EVmTu3xn2yR152hSwgSBW8tgadgyPFCSK+jwLYVD12bjuPvln8BNxEGgpFwTmfWX6NnX9N9vK2vfwlNra1z2/ZTDo333NvO2TypXRVDNA0QSCSSwmBdU7xD2JR19gUsV6/BPyIeNrPt1W9zHI39MIeUOitVsFP8NGv8LO/2tCouNG5nMYrbY0g2I6I3uYIl9JaHtSH6Hr3PdWSfdMTYPN0BKMPppK4oYs0mRUJIwAlK3aIcwL6lNMzi20vzjGDJu/+/LcSpNwcAZx/bw0KLtyRjcX01ZmXJjwLCtIJVBvltx4RWfhLErHHH3xJqO7cjqM7/eTJRI8xUGmkIvdIVqGxSnmrL0Ghg5ambDUdoEq+5IzH8/JNXqsN3a+2MT5MT0Uu2XFq9MZzvqmzJliT7gKt+RrAChER49gHoKzUW4OD+Jek9Zjd0kCOJpxbM3/w/n7l+F1zGZYzqmSG8EG2gdm/LVcIMchGXbjZ6nrhP6E82uJpvfOlBGvqJlXqNZGqkKV1PuaOBhsPFa3RLJWiv0M3K7DNVuzpY6suXoTz967fxqTqLrdw3HIOJ5I7+arDNlHhXZmu22Xo4c5DV6c64CWt2mRm8DbqAhjhN7p9XTR7+drY7UcluX074w==
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: sa-platform
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: sa-platform
        app.kubernetes.io/part-of: sa-platform
        app.kubernetes.io/version: 2.0.0
        helm.sh/chart: sa-platform-3.0.0
      name: sa-platform-order-service-secret
      namespace: sa-p8-prod
    type: Opaque
