---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sa-platform-db-credentials
  namespace: sa-p8-prod
spec:
  encryptedData:
    postgres-password: AgA/Azh1Yf3l/taLVvISlXB/uKZaucT152Nz+5Z38wKEsTqBZzzF3l79gisYOC1ZHLolkvRa+1IJ36s0wx91+zyEh7Vh6nXDOJMOBNt1eEE5gZfz1Y3XuXS8Nh41dk90i6EiEjsSGDkN45Fppa0SUl5LjFCpiLhlWtwuW92MF5zGyu01SFEKVWBQpRLhnyA7LjnnPqK99f6Q44QdJJpd8KVE/GWVZYfohuEyNSvbDASF7UHfelb6oEQJo87mb80yFTAwjTZQ5YtDzhRnBOASyNoo/2mYQ8ou7SzC1qvaffUQdw71708PFJu9nm4qk2429lrZwBMa2exZsk1LsuhdNov1YwPlSK9SN7HFXQQmHTlmcoTEY61pOKN7oQVT24ybAHlf8UBtbNgzcsXAXkOAOlZSbdupUQ6eXyL4YShxxyb25B8g+UiAOtdpXQfkZXM3ox6FYsx0hROyNXW35CtQ5FgdrTkE047cqNQjPt1cu0BA+8kRRGXpeT4kPISU8Js8RH2nxYVjWaFBIv0FYsR27B3uHPpPgIKaFLowIIAYmfevX61RGdkZTKSZzCdWB0sfNcQcjzlXwyiyhUrkFpwGaW8eFgIleNTCvblxJHwVhOvOoJBW6cGaG707p8rgP2Y1bsfWe88Gflav9xB1nE95kV3BXuWM6SXlvIAp2h1kganmL9LrVh+ANCwScXspxLttUR9j9OFe3YFp11/BfsqAoC6tzj++PMuOJ9V5uKcmySxNtg==
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: sa-platform
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: sa-platform
        app.kubernetes.io/part-of: sa-platform
        app.kubernetes.io/version: 2.0.0
        helm.sh/chart: sa-platform-3.0.0
      name: sa-platform-db-credentials
      namespace: sa-p8-prod
    type: Opaque
