---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sa-platform-catalog-service-secret
  namespace: sa-p8-prod
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgATS03LjocWC3Dg122qmcSNIRqzCiba1fpY16Ei7REFb3bEzuut30Z/cg8ojeb+uItRLudDik9gKWZk+UYTbBWvZqAu2cmFQYhVFs1G0TGstyk+DXVCaAPKjfMdLx8mFQA1QMb0Ms54gkCv63rR2U73O2GlS2MhucVKS7UnfNsyPMn4T9zc+nZQmLiSFUUSUP0eFNBFUEOO9QwU7HogOCoA2+o90xgUX2jEM1mx4uR8pjlQkdGIDfI/rZFr6kJWiVJhGYtHiMsOqPWsE4YH872crqOUj9yL4niBIjXiCTCK8ItSD/K9bckaor93PtSauZEakLzz0ikjKBc916re0oSe0bdGqA3Es5nAQml7tHeJKX59PTmKKLV63T7HQDyK3x5QySXh8IR+CJbaONMctl0m2qcseCVY7IgmtIWdwNjs3w0eomwIuSOazjbzof7f11Ucwe99dd+0hBxY06oGTKacIGiGGqR0ctAUjrxdfK2SL1Xof6AiPLrL0hoVd67L5ANgDOwcBrQewAnjZU5dYP7puN6ulAo00T7oxRZufGD4dm665Wh7yGffGaeQVJziB59HR+Wiup/BJbfxwRAyhonvlTPzuj6C5bPDz/ajXDmc/Hm0eAjtNzYOfvXyXKCE1kkJzyJgJV1xzJoa9n7MTSUQkHAsn8WBCmdLui2RR6DIVLlmh93dOTbJYg5bQBrXpH2KkzKBxvAjU8OnqwUP79tVtPmp6q/9U0NKyZlBfY0oLg==
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: sa-platform
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: sa-platform
        app.kubernetes.io/part-of: sa-platform
        app.kubernetes.io/version: 2.0.0
        helm.sh/chart: sa-platform-3.0.0
      name: sa-platform-catalog-service-secret
      namespace: sa-p8-prod
    type: Opaque
