---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sa-platform-broker-credentials
  namespace: sa-p8-prod
spec:
  encryptedData:
    rabbitmq-erlang-cookie: AgAVa9D5oyycCdH3M2iK60aQZn+T/gmBzKaK7oc/ebB+TLnRJG9PQ51kVB6LfuUmpzEm1WJoWTiR/NIkvq/yFweAzRlTpXDxTgBC9G3N5gqeDM94o1TKaOaBybfqBmPuBVLAhEO5i5IxpISfdVd+WxH3N0uXCLc1FG8fCs0b6wQreDZcfZpFmWj2IgBXro1dDyWaTutFYrClwA7EMq5PBUxvpnmwh4HESmT1N65Ctd1q/6gLCDbsvkTTSwhnM5CCpvILqIImMXFGsQJcYnarcf3wKW7u+rSl/8odxEozNKYAJbF1VoEPLdY8nnuN49Rwt+VjgQbGpNzzXKyf0MVn/zhgNtYCKmMSf2Kp1TPlhwwDtVQ1ov58ozDdQp4a47v3LTwwKQxAF5Bp8CUvrx1cQSjXUeHu7WjUBsGiWmsYq68r4tmhLZdsP+ArBqXHFaxVDhelqlBe4KJLO/owsPwRukpgSMwpESEj01Ok4s0BOULvHXB35p1cpEvjoqmr4b6dhwrPXP2uFCpEoEDddJP9ofcWZ3sylwSX/e9m07cM906M+aFXEYBb3n0ua41UsIBJVWEP8Yqoh0jFu7VEalLjebKiEZTu8wXSwHT54wEMNuGvKryE+njEsaeI1b6dLEiaariru0iqEgZ/1MawfaJIb9K8efrFGXdmwfF77Sn74nBqshhuta9rFct7IQz7yEy/AyGB4bL+B61bJm2zvKRueXcveVG1cENO+FX0DZXiJs6vgQ==
    rabbitmq-password: AgApTpQ602ILDk4AJbLGHNXguc1ylciRViB70U26Ib8ZZRH7NtIOShsDOoe/58ZaiMlFbEwqqr+BPZm46xbnkYYSB6Lw4Do7/I2/wdjrLSnIXudpU/DZ4XRHpQog5bXJnBkNN7TKyQUr68h1MVqx/Taq8lRQz8HJqkzd4ITaa47zYV61Smq3/CAb9qb7bXR4kYZhLHL1G2puUy9QUs4jc9r0Z2zdSdtQBbInGlH6sShkwUZvMonpUKmow2BXyW79s2mBfStqLV3CNxeVvGYXblcrN+yFOX0Me1gVjUWDqoQpLV2zq8SEYwGgrUUg/zrWE6Zt8Kde44KDk2ITuexI2qMZ256aj5ZMUUW47YnhJQbywlHFNgOBCEkulnRlL0UW1UzJyLY4T6KnwQDTigASq9lIMN4yMaDbpHSvDjTtCftJy0wjrEHDc4KzuFoYzE+x4RD8XKZPdGPcgB5ct0OINRpjHW8lf4C/Ubd9dAq4+sdbt0nSw2dRiZSuAAfun0DCNed+L7qIlnrmE7DM0LB/Uo2Crylf5TmNc1W4RUnwXfCNNLDWfhNmB7UkJqDqYvXtDYXZD/baqo21F6tEgQulQjK3D9LAwb0pO1YtVJFOL2J7h8rA/bDbfYWhbaF5sviQvUuvnrSVbijOmgNedu1MXsYqoIFWlQeSANMP/p3mnXFTK7CE6hA0wy9EVPb8uE6GqdUo5daXtZ4hzfwWHk+X90Jup80ySSVsaEaOfSPIianngQ==
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: sa-platform
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: sa-platform
        app.kubernetes.io/part-of: sa-platform
        app.kubernetes.io/version: 2.0.0
        helm.sh/chart: sa-platform-3.0.0
      name: sa-platform-broker-credentials
      namespace: sa-p8-prod
    type: Opaque
